def Function1(Ef_inv, Con_LOLP, Con_dummy, prompt3, flag):

    prompt1_result = []
    prompt2_result = []

    for prompt2 in range(1, 21):
        for prompt1 in range(1, 21):

            # Types of Power Pattern generated by Wind Turbine during a one day(1~20)
            P_wind = [0.81, 1.00, 0.57, 0.38, 0.22, 0.35, 0.44, 0.36, 0.57, 0.82, 0.58, 0.33, 0.35, 0.64, 0.64, 0.22,
                      0.18, 0.10, 0.05, 0.08, 0.15, 0.08, 0.14, 0.13]

            # Types of Power Pattern generated by Photovoltaic during a one day(5~25)
            P_pv = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.5, 0.7, 0.9, 1.0, 0.9, 0.8, 0.7, 0.53125, 0.2, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0]

            # Types of Load Pattern during a one day(5~9)
            P_load = [0.33, 0.32, 0.32, 0.31, 0.30, 0.30, 0.34, 0.40, 0.50, 0.70, 0.69, 0.60, 0.55, 0.70, 0.68, 0.60,
                      0.53, 0.5, 0.47, 0.45, 0.4, 0.36, 0.34, 0.33]

            # Choice a pattern of wind turbine, Photovoltaic and Load
            P_wind = [round(prompt1 * value, 3) for idx, value in enumerate(P_wind)]
            P_pv = [round((prompt2 + 4) * value, 3) for idx, value in enumerate(P_pv)]
            P_load = [round((prompt3 + 4) * value, 3) for idx, value in enumerate(P_load)]

            # Enter battery data, initial SOC(%), SOC_min(%), SOC_max(%), P_bc(kW), P_bd(kW)
            C_bat = 20  # Capacity(kWh)
            SOC_ini = 30  # initial SOC of battery
            SOC_min = 10  # minimum SOC of battery
            SOC_max = 90  # maximum SOC of battery
            P_bc = [0] * 24  # output of battery in charge mode
            P_bd = [0] * 24  # output of battery in discharge mode
            Ef_bc = 0.9  # efficiency of battery in charge mode
            Ef_bd = 0.85  # efficiency of battery in discharge mode
            r_sd = 0.002  # self - discharge rate of battery

            # Enter dummy load capacity(kW)
            P_dummy = [0] * 24
            E_dummy = 0

            # Enter diesel generator capacity(kW), output(kW) and efficiency
            P_dgr = 10
            P_dg = [0] * 24
            Ef_dg = 0.95

            # NPSP algorithm
            t = 1  # initial time
            LOLP = [0] * 24  # initial LOLP at each time
            LOLP_sum = 0
            E_bat = (C_bat * SOC_ini) / 100  # initial kWh capacity of battery at each time
            SOC = [0] * 24  # initial SOC of battery at each time

            # iteration for day calculation(24h)
            for t in range(24):

                SOC[t] = E_bat / C_bat * 100  # SOC calculation of battery at each time

                if P_wind[t] > P_load[t]:  # occurred surplus energy in HRES system
                    if SOC[t] < SOC_max:  # check SOC of battery whether the SOC has enough
                        P_bc[t] = (P_wind[t] - P_load[t] * Ef_inv + P_pv[t]) * Ef_bc  # calculate charge capacity of battery
                        E_bat = E_bat * (1 - r_sd) + P_bc[t] * Ef_bc  # accumulate capacity of battery
                    else:
                        P_bc[t] = 0  # calculate charge capacity of battery
                        P_dummy[t] = (P_wind[t] - P_load[t]) + P_pv[t] * Ef_inv  # calculate capacity of dummy loads to cover surplus energy in HRES system
                        E_dummy = E_dummy + P_dummy[t]  # accumulate capacity of dummy loads to check total used capacity of dummy loads

                if P_wind[t] <= P_load[t] and (P_wind[t] + P_pv[t] * Ef_inv) > P_load[
                    t]:  # occurred surplus energy in HRES system
                    if SOC[t] < SOC_max:  # check SOC of battery whether the SOC has enough
                        P_bc[t] = (P_wind[t] + P_pv[t] * Ef_inv - P_load[t]) * Ef_bc * Ef_inv  # calculate charge capacity of battery
                        E_bat = E_bat * (1 - r_sd) + P_bc[t] * Ef_bc  # accumulate capacity of battery
                    else:
                        P_bc[t] = 0  # calculate charge capacity of battery
                        P_dummy[t] = P_wind[t] + P_pv[t] * Ef_inv - P_load[t]  # calculate capacity of dummy loads to cover surplus energy in HRES system
                        E_dummy = E_dummy + P_dummy[t]  # accumulate capacity of dummy loads to check total used capacity of dummy loads

                if P_wind[t] <= P_load[t] and (P_wind[t] + P_pv[t] * Ef_inv) <= P_load[
                    t]:  # occurred deficit energy in HRES system
                    if SOC[t] > SOC_min:  # check SOC of battery whether the SOC has lack of capacity
                        P_bd[t] = (P_pv[t] - (P_load[t] - P_wind[t]) / Ef_inv) * Ef_bd  # calculate discharge capacity of battery
                        E_bat = E_bat * (1 - r_sd) - abs(P_bd[t]) * Ef_bd  # accumulate capacity of battery
                    else:
                        P_bd[t] = 0  # calculate charge capacity of battery
                        P_dg[t] = (P_load[t] - P_wind[t] - P_pv[t] * Ef_inv) / Ef_dg  # calculate capacity of diesel generator to cover deficit energy in HRES system
                        if P_dg[t] > P_dgr:  # check the capacity of diesel generator whether it exceeds rated capacity of diesel generator
                            LOLP[t] = 1  # evaluate LOLP at time t
                            LOLP_sum = LOLP_sum + LOLP[t]  # accumulate LOLP at each time
                        else:
                            LOLP[t] = 0  # evaluate LOLP at time t

            # check capacity of HRES with constraints of LOLP and dummy loads
            if E_dummy <= 0:
                pass
            # print('Need to increasing capacity of PV or WT.\n')
            else:
                if E_dummy > max(P_load):
                    pass
                # print('Need to decreasing capacity of PV or WT.\n')
                else:
                    if LOLP_sum / t > Con_LOLP:
                        pass
                    # print('Need to increasing capacity of PV or WT.\n')
                    else:
                        # print('Present capacities of PV and WT are optimal.\n')
                        prompt1_result.append(prompt1)
                        prompt2_result.append(prompt2)

    return prompt1_result, prompt2_result

def Function2(Ef_inv, Con_LOLP, Con_dummy, prompt1, prompt2, prompt3, flag):

    # Types of Power Pattern generated by Wind Turbine during a one day(1~20)
    P_wind = [0.81, 1.00, 0.57, 0.38, 0.22, 0.35, 0.44, 0.36, 0.57, 0.82, 0.58, 0.33, 0.35, 0.64, 0.64, 0.22, 0.18, 0.10, 0.05, 0.08, 0.15, 0.08, 0.14, 0.13]

    # Types of Power Pattern generated by Photovoltaic during a one day(5~25)
    P_pv = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.5, 0.7, 0.9, 1.0, 0.9, 0.8, 0.7, 0.53125, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # Types of Load Pattern during a one day(5~9)
    P_load = [0.33, 0.32, 0.32, 0.31, 0.30, 0.30, 0.34, 0.40, 0.50, 0.70, 0.69, 0.60, 0.55, 0.70, 0.68, 0.60, 0.53, 0.5, 0.47, 0.45, 0.4, 0.36, 0.34, 0.33]

    # Choice a pattern of wind turbine, Photovoltaic and Load
    P_wind = [round(prompt1 * value, 3) for idx, value in enumerate(P_wind)]
    P_pv = [round((prompt2 + 4) * value, 3) for idx, value in enumerate(P_pv)]
    P_load = [round((prompt3 + 4) * value, 3) for idx, value in enumerate(P_load)]

    # Enter battery data, initial SOC(%), SOC_min(%), SOC_max(%), P_bc(kW), P_bd(kW)
    C_bat = 20				# Capacity(kWh)
    SOC_ini = 30			# initial SOC of battery
    SOC_min = 10			# minimum SOC of battery
    SOC_max = 90			# maximum SOC of battery
    P_bc = [0] * 24		    # output of battery in charge mode
    P_bd = [0] * 24		    # output of battery in discharge mode
    Ef_bc = 0.9			    # efficiency of battery in charge mode
    Ef_bd = 0.85			# efficiency of battery in discharge mode
    r_sd = 0.002			# self - discharge rate of battery

    # Enter dummy load capacity(kW)
    P_dummy = [0] * 24
    E_dummy = 0

    # Enter diesel generator capacity(kW), output(kW) and efficiency
    P_dgr = 10
    P_dg = [0] * 24
    Ef_dg = 0.95

    # NPSP algorithm
    t = 1							# initial time
    LOLP = [0] * 24					# initial LOLP at each time
    LOLP_sum = 0
    E_bat = (C_bat * SOC_ini) / 100	# initial kWh capacity of battery at each time
    SOC = [0] * 24					# initial SOC of battery at each time

    # iteration for day calculation(24h)
    for t in range(24):

        SOC[t] = E_bat / C_bat * 100     # SOC calculation of battery at each time

        if P_wind[t] > P_load[t]: # occurred surplus energy in HRES system
            if SOC[t] < SOC_max: # check SOC of battery whether the SOC has enough
                P_bc[t] = (P_wind[t] - P_load[t] * Ef_inv + P_pv[t]) * Ef_bc #calculate charge capacity of battery
                E_bat = E_bat * (1 - r_sd) + P_bc[t] * Ef_bc         # accumulate capacity of battery
            else:
                P_bc[t] = 0 # calculate charge capacity of battery
                P_dummy[t] = (P_wind[t] - P_load[t]) + P_pv[t] * Ef_inv # calculate capacity of dummy loads to cover surplus energy in HRES system
                E_dummy = E_dummy + P_dummy[t] # accumulate capacity of dummy loads to check total used capacity of dummy loads

        if P_wind[t] <= P_load[t] and (P_wind[t] + P_pv[t] * Ef_inv) > P_load[t]: # occurred surplus energy in HRES system
            if SOC[t] < SOC_max: # check SOC of battery whether the SOC has enough
                P_bc[t] = (P_wind[t] + P_pv[t] * Ef_inv - P_load[t]) * Ef_bc * Ef_inv # calculate charge capacity of battery
                E_bat = E_bat * (1 - r_sd) + P_bc[t] * Ef_bc # accumulate capacity of battery
            else:
                P_bc[t] = 0  # calculate charge capacity of battery
                P_dummy[t] = P_wind[t] + P_pv[t] * Ef_inv - P_load[t]  # calculate capacity of dummy loads to cover surplus energy in HRES system
                E_dummy = E_dummy + P_dummy[t]  # accumulate capacity of dummy loads to check total used capacity of dummy loads

        if P_wind[t] <= P_load[t] and (P_wind[t] + P_pv[t] * Ef_inv) <= P_load[t]: # occurred deficit energy in HRES system
            if SOC[t] > SOC_min: # check SOC of battery whether the SOC has lack of capacity
                P_bd[t] = (P_pv[t] - (P_load[t] - P_wind[t]) / Ef_inv) * Ef_bd # calculate discharge capacity of battery
                E_bat = E_bat * (1 - r_sd) - abs(P_bd[t]) * Ef_bd # accumulate capacity of battery
            else:
                P_bd[t] = 0 # calculate charge capacity of battery
                P_dg[t] = (P_load[t] - P_wind[t] - P_pv[t] * Ef_inv) / Ef_dg # calculate capacity of diesel generator to cover deficit energy in HRES system
                if P_dg[t] > P_dgr: # check the capacity of diesel generator whether it exceeds rated capacity of diesel generator
                    LOLP[t] = 1 # evaluate LOLP at time t
                    LOLP_sum = LOLP_sum + LOLP[t] # accumulate LOLP at each time
                else:
                    LOLP[t] = 0 # evaluate LOLP at time t

    # check capacity of HRES with constraints of LOLP and dummy loads
    if E_dummy <= 0:
        pass
      # print('Need to increasing capacity of PV or WT.\n')
    else:
        if E_dummy > max(P_load):
            pass
          # print('Need to decreasing capacity of PV or WT.\n')
        else:
            if LOLP_sum / t > Con_LOLP:
                pass
              # print('Need to increasing capacity of PV or WT.\n')
            else:
                # print('Present capacities of PV and WT are optimal.\n')
                pass

    return P_wind, P_dummy, P_pv, P_bc, P_bd, P_load, SOC